# Generated by Django 5.2.6 on 2025-10-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offers'),
        ),
    ]
