# Generated by Django 5.2.6 on 2025-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
