# Generated by Django 5.2.6 on 2025-10-26 08:34

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_register_first_name_register_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=300, unique=True, validators=[customer.validators.validate_real_email]),
        ),
    ]
