# Generated by Django 5.2.6 on 2025-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/'),
        ),
    ]
