# Generated by Django 5.2.6 on 2025-10-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_register_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='image',
            new_name='profile_image',
        ),
    ]
