# Generated by Django 5.2.6 on 2025-11-10 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_image_register_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s,.\\-]+$', 'Please enter a valid address', 'invalid_symbols')]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Please enter a valid name', 'invalid_city_state')]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Please enter a valid name', 'invalid_city_state')]),
        ),
    ]
