# Generated by Django 5.2.6 on 2025-11-13 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_useraddress_address_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='full_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Please enter a valid name', 'invalid name')]),
        ),
    ]
