# Generated by Django 5.2.6 on 2025-10-14 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='code',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='disciptions',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='expir_at',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='status',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='user',
        ),
        migrations.AddField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='expire_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupons',
            name='min_cart_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='use_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
