# Generated by Django 5.2.6 on 2025-10-14 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupons_code_remove_coupons_disciptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expire_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
