# Generated by Django 5.2.6 on 2025-11-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupons_expire_at'),
        ('orders', '0004_rename_coupon_cart_coupon_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='use_limit',
        ),
        migrations.AddField(
            model_name='coupons',
            name='use_limit_per_user',
            field=models.PositiveIntegerField(default=1, help_text='How many times each user can use this coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupons')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usage', to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='coupon_coup_coupon__13a37a_idx'), models.Index(fields=['user', '-used_at'], name='coupon_coup_user_id_42ce03_idx')],
            },
        ),
    ]
