# Generated by Django 5.2.6 on 2025-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_remove_coupons_use_limit_coupons_use_limit_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Choose between percentage discount or fixed amount', max_length=20),
        ),
        migrations.AddField(
            model_name='coupons',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (only for percentage type)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual discount amount applied', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='For percentage: enter value like 10 for 10%. For fixed: enter amount like 100 for ₹100', max_digits=5),
        ),
    ]
