# Generated by Django 5.2.6 on 2025-10-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.productpage'),
        ),
    ]
