# Generated by Django 5.2.6 on 2025-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={},
        ),
        migrations.AddField(
            model_name='offers',
            name='applies_to',
            field=models.CharField(blank=True, choices=[('referrer', 'Referrer Only'), ('referee', 'Referee Only'), ('both', 'Both Referrer and Referee')], help_text='Specify who the referral offer applies to', max_length=20, null=True),
        ),
    ]
