# Generated by Django 5.2.6 on 2025-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offers_options_offers_applies_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AddField(
            model_name='offers',
            name='fixed_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed bonus amount for referral reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='offers',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional percentage bonus', max_digits=5),
        ),
        migrations.AddField(
            model_name='offers',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, help_text='Reward validity duration in days'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='applies_to',
            field=models.CharField(choices=[('referrer', 'Referrer'), ('referee', 'Referee'), ('both', 'Both')], default='both', help_text='Who this referral offer applies to', max_length=20),
        ),
    ]
