# Generated by Django 5.2.6 on 2025-11-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
