# Generated by Django 5.2.6 on 2025-09-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitems',
            old_name='wish_list_id',
            new_name='wish_list',
        ),
    ]
