# Generated by Django 5.2.6 on 2025-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
