# Generated by Django 5.2.6 on 2025-10-14 07:19

import django.db.models.deletion
import orders.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('second_mob', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=6, validators=[orders.models.realistic_pin_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Processed'), (3, 'Delivered'), (4, 'Cancelled'), (5, 'Return Requested'), (6, 'Return Approved'), (7, 'Returned')], default=0)),
                ('return_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('item_cancel_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(0, 'Cash on Delivery'), (1, 'Online Payment'), (2, 'Wallet Payment')], default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Payment Pending'), (1, 'Payment Paid'), (2, 'Payment Failed'), (3, 'Payment Refunded')], default=0)),
                ('order_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Processed'), (3, 'Delivered'), (4, 'Rejected'), (5, 'Return Requested'), (6, 'Return Approved'), (7, 'Returned')], default=0)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay Signature for verification', max_length=255, null=True)),
                ('paypal_order_id', models.CharField(blank=True, help_text='PayPal Order ID for tracking', max_length=100, null=True)),
                ('paypal_payer_id', models.CharField(blank=True, help_text='PayPal Payer ID', max_length=100, null=True)),
                ('paypal_capture_id', models.CharField(blank=True, help_text='PayPal Capture ID', max_length=100, null=True)),
                ('return_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('order_Id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_return_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('return_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField(choices=[(0, 'CART_STAGE'), (2, 'ORDER_PROCESSED'), (1, 'ORDER_CONFIRMED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='orders.cart')),
            ],
        ),
    ]
