# Generated by Django 5.2.6 on 2025-10-14 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item', to='products.productpage'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariants'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productpage'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariants'),
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupons'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderaddress'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('product', 'owner', 'variant')},
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_3bcb80_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['order_status'], name='orders_orde_order_s_a2e7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_f62fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['razorpay_order_id'], name='orders_orde_razorpa_44f2a5_idx'),
        ),
    ]
