# Generated by Django 5.2.6 on 2025-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='return_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
