# Generated by Django 5.2.6 on 2025-10-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupons_code_remove_coupons_disciptions_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paypal_capture_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paypal_payer_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupons'),
        ),
    ]
