# Generated by Django 5.2.6 on 2025-10-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_paypal_capture_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='coupon_code',
        ),
    ]
