# Generated by Django 5.2.6 on 2025-11-10 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_coupon_cart_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='address',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s,.\\-_\\/]+$', 'Please enter a valid address.', 'invalid_address_symbols')]),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'City/State must only contain letters and spaces.', 'invalid_city_state')]),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='state',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'City/State must only contain letters and spaces.', 'invalid_city_state')]),
        ),
    ]
