# Generated by Django 5.2.6 on 2025-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderaddress_address_alter_orderaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='The estimated date when the order is expected to be delivered.', null=True),
        ),
    ]
