# Generated by Django 5.2.6 on 2025-10-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('offer', '0001_initial'),
        ('varients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, upload_to='products/')),
                ('image5', models.ImageField(blank=True, upload_to='products/')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('old_price', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('block', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorypage')),
                ('offer', models.ForeignKey(blank=True, limit_choices_to={'offer_type': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offers')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='products.productpage')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varients.varient')),
            ],
            options={
                'unique_together': {('product', 'variant')},
            },
        ),
    ]
