# Generated by Django 5.2.6 on 2025-10-24 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product_variant')},
        ),
    ]
